"""
src/bookable/migrate_cache.py

Platform-Stable Cache Migration & Provenance Verification Tool:
- Re-keys production cache entries to source-identity SHA256 keys:
    SHA256(PDF_SHA256 + page/range + prompt_version + model + schema_version)
- Migrates ONLY cache entries proven to have been generated by current production prompts.
- Preserves raw LLM response contents unchanged.
- Excludes all Step 6 scratch/answer-guided cache entries and stale experimental keys.
- Ensures existing legacy cache files remain byte/content unchanged.
"""

from __future__ import annotations

import sys
import json
import hashlib
from pathlib import Path
from typing import Dict, Any, List, Tuple

_SRC_DIR = Path(__file__).resolve().parent.parent
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))

from bookable.classify import render_pdf_for_classification
from bookable.extract import _render_segment_pages, _EXTRACTION_PROMPT_TEMPLATE
from bookable.llm import CACHE_DIR, compute_cache_key, compute_source_cache_key, SCHEMA_VERSION


def migrate_production_cache(
    docs_dir: Path | str = "documents",
    cache_dir: Path | str = CACHE_DIR,
    model: str = "gemini-3.1-flash-lite",
    dry_run: bool = False
) -> Dict[str, Any]:
    """
    Perform safe migration of production cache entries.
    Returns audit statistics dictionary.
    """
    docs_path = Path(docs_dir)
    cache_path = Path(cache_dir)

    all_cache_files = {f.stem: f for f in cache_path.glob("*.json")}
    pdf_files = sorted(docs_path.glob("*.pdf"), key=lambda p: p.name.lower())

    migrated_cls = 0
    migrated_ext = 0
    proven_keys = set()
    ambiguous_keys = []

    # Known Step 6 answer-guided scratch keys to explicitly verify exclusion
    known_scratch_keys = {
        '54b92a96c0d80409600d793778053e2437c535f37f27ad4a21ea5d95b9723653',  # HLD-03
        '2bb37c803d87d96c45815f0d4186f5e323af06d281edbf25768f9237b73e4807',  # INV-06
        '9e9075aab2dec6c9b6005685f899d818e094b413df61f17a98f6b6bbca8d022a',  # INV-09
        '616a7c2a3cea6c3b09987e32f4ba235b0882a4ea484fcc486bd6a2978ba72f09',  # INV-13
        '2d18f4a3328115ea8f889c1b3c44580a01a3549adaad73c1a7cd15b8afd515af',  # INV-16
        '8d73406fc40091028e770898f9f43bd86183236750f1957bb82cb3e86ade7554',  # INV-19
        '7a9cfc264fd5d6a53a51663718be6d731f8eec0dbb4ada15698e54ad212b2e2c',  # INV-21
        '524031bd270724b6941dfd6c8d915b1afdef0ddef6df0c162b9ad5060765c424',  # INV-35
    }

    # 1. Classification migration
    for pdf in pdf_files:
        pdf_sha256 = hashlib.sha256(pdf.read_bytes()).hexdigest()
        pdata, imgs = render_pdf_for_classification(pdf)
        th = [f"Page {x['page_num']}: {x['text'][:600]}" for x in pdata if x["has_text"]]
        total_pages = len(pdata)
        prompt = (
            "You are an expert Accounts Payable (AP) Document Classification & Page Segmentation Engine for an ERP system.\n"
            f"Document filename: {pdf.name}\n"
            f"Total pages rendered: {total_pages}\n\n"
            "TASK:\n"
            "1. Examine the visual layout and text of all pages.\n"
            "2. Determine the Document Type:\n"
            "   - 'INVOICE': Vendor commercial invoice for goods/services purchased.\n"
            "   - 'CREDIT_MEMO': Credit note / credit memo adjusting payable balance.\n"
            "   - 'CUSTOMS_DOCUMENT': Customs declaration, customs consolidated invoice, or border manifest (NON-PAYABLE for AP).\n"
            "   - 'STATEMENT': Account statement, summary billing statement without line item charge ledger (NON-PAYABLE).\n"
            "   - 'NON_PAYABLE': Shipping note, purchase order, internal checklist, or non-payable attachment.\n"
            "3. Make a Processing Decision:\n"
            "   - 'PROCESS': Bookable payable ready for extraction.\n"
            "   - 'DECLINE': Non-payable document (customs declaration, statement, internal form).\n"
            "   - 'SPLIT': Multi-invoice document containing separate distinct payables.\n"
            "   - 'MANUAL_REVIEW': Uncertain or ambiguous layout.\n"
            "4. Document Count: Integer count of distinct bookable payable documents found (0 if DECLINE).\n"
            "5. GENERAL SEGMENTATION RULE (Rule 9):\n"
            "   A new payable begins ONLY when there is a new invoice number OR a new primary seller/billing party.\n"
            "   Later pages that repeat the same PO/reference/amount and belong to a third party (e.g. utility bill, delivery note,\n"
            "   or backup statement attached as pass-through documentation) are ATTACHMENTS of the parent payable, NOT separate payables.\n"
            "   Do NOT double-count the same amount. Group such attached pages together with the parent payable into ONE segment [1..N].\n"
            "6. Rationale: Clear plain-English explanation detailing WHY this classification was chosen based on visible features.\n\n"
            "Respond ONLY in valid JSON matching this schema:\n"
            "{\n"
            '  "filename": "' + pdf.name + '",\n'
            '  "document_type": "INVOICE | CREDIT_MEMO | CUSTOMS_DOCUMENT | STATEMENT | NON_PAYABLE | OTHER",\n'
            '  "decision": "PROCESS | DECLINE | SPLIT | MANUAL_REVIEW",\n'
            '  "document_count": 1,\n'
            '  "page_segmentation": [\n'
            '    {\n'
            '      "segment_id": 1,\n'
            '      "type": "INVOICE | CREDIT_MEMO | SUPPORTING_DOC | DECLINED_DOC",\n'
            '      "pages": [1],\n'
            '      "description": "Short section summary"\n'
            '    }\n'
            '  ],\n'
            '  "decline_reason": "Explanation if decision is DECLINE, else empty string",\n'
            '  "rationale": "Clear grounded explanation"\n'
            "}"
        )
        legacy_key = compute_cache_key(prompt, imgs, th, detail="low")
        if legacy_key in all_cache_files:
            proven_keys.add(legacy_key)
            rendered_pages = [x["page_num"] for x in pdata]
            source_key = compute_source_cache_key(
                pdf_sha256=pdf_sha256,
                page_numbers=rendered_pages,
                prompt_version="v1_classify",
                model=model,
                schema_version=SCHEMA_VERSION
            )

            # Read existing
            with open(all_cache_files[legacy_key], "r", encoding="utf-8") as fp:
                existing = json.load(fp)

            new_entry = {
                "data": existing["data"],  # Raw response unchanged
                "meta": dict(existing.get("meta", {}))
            }
            new_entry["meta"]["source_pdf_sha256"] = pdf_sha256
            new_entry["meta"]["page_range"] = sorted(rendered_pages)
            new_entry["meta"]["prompt_version"] = "v1_classify"
            new_entry["meta"]["model"] = model
            new_entry["meta"]["schema_version"] = SCHEMA_VERSION
            new_entry["meta"]["legacy_cache_key"] = legacy_key

            if not dry_run:
                target_file = cache_path / f"{source_key}.json"
                with open(target_file, "w", encoding="utf-8") as fp:
                    json.dump(new_entry, fp, indent=2, ensure_ascii=False)

            migrated_cls += 1

    # 2. Extraction migration
    for pdf in pdf_files:
        pdf_sha256 = hashlib.sha256(pdf.read_bytes()).hexdigest()
        pdata_cls, _ = render_pdf_for_classification(pdf)
        rendered_pages_cls = [x["page_num"] for x in pdata_cls]
        source_key_cls = compute_source_cache_key(
            pdf_sha256=pdf_sha256,
            page_numbers=rendered_pages_cls,
            prompt_version="v1_classify",
            model=model,
            schema_version=SCHEMA_VERSION
        )

        cls_file = cache_path / f"{source_key_cls}.json"
        if not cls_file.exists():
            continue

        with open(cls_file, "r", encoding="utf-8") as fp:
            cls_data = json.load(fp)["data"]

        segments = cls_data.get("page_segmentation", [])
        for seg in segments:
            seg_id = seg.get("segment_id", 1)
            seg_type = seg.get("type", "INVOICE")
            pages = seg.get("pages", [1])
            desc = seg.get("description", "")
            if seg_type in ["ATTACHMENT", "DECLINED", "DECLINED_DOC"]:
                continue

            pdata, imgs = _render_segment_pages(pdf, pages, dpi=150)
            th = [f"Page {x['page_num']}: {x['text'][:800]}" for x in pdata if x["has_text"]]
            seg_ctx = f"Segment {seg_id} of type '{seg_type}'. Pages: {pages}. Description: {desc}. File: {pdf.name}."
            prompt = _EXTRACTION_PROMPT_TEMPLATE.replace("<<<SEGMENT_CONTEXT>>>", seg_ctx)
            legacy_key = compute_cache_key(prompt, imgs, th, detail="high")

            if legacy_key in all_cache_files:
                proven_keys.add(legacy_key)
                source_key = compute_source_cache_key(
                    pdf_sha256=pdf_sha256,
                    page_numbers=pages,
                    prompt_version="v1_extract",
                    model=model,
                    schema_version=SCHEMA_VERSION
                )

                with open(all_cache_files[legacy_key], "r", encoding="utf-8") as fp:
                    existing = json.load(fp)

                new_entry = {
                    "data": existing["data"],  # Raw response unchanged
                    "meta": dict(existing.get("meta", {}))
                }
                new_entry["meta"]["source_pdf_sha256"] = pdf_sha256
                new_entry["meta"]["page_range"] = sorted(pages)
                new_entry["meta"]["prompt_version"] = "v1_extract"
                new_entry["meta"]["model"] = model
                new_entry["meta"]["schema_version"] = SCHEMA_VERSION
                new_entry["meta"]["legacy_cache_key"] = legacy_key

                if not dry_run:
                    target_file = cache_path / f"{source_key}.json"
                    with open(target_file, "w", encoding="utf-8") as fp:
                        json.dump(new_entry, fp, indent=2, ensure_ascii=False)

                migrated_ext += 1

    total_migrated = migrated_cls + migrated_ext
    excluded_keys = set(all_cache_files.keys()) - proven_keys
    scratch_excluded = len(excluded_keys.intersection(known_scratch_keys))
    other_excluded = len(excluded_keys) - scratch_excluded

    report = {
        "production_entries_found": total_migrated,
        "classification_migrated": migrated_cls,
        "extraction_migrated": migrated_ext,
        "total_migrated": total_migrated,
        "excluded_count": len(excluded_keys),
        "excluded_step6_scratch_count": scratch_excluded,
        "excluded_stale_or_experimental_count": other_excluded,
        "ambiguous_count": len(ambiguous_keys),
        "reasons_for_exclusion": [
            f"{scratch_excluded} Step 6 scratch/answer-guided entries generated with custom hints containing target answers",
            f"{other_excluded} stale, experimental, or prior-version cache entries not generated by production prompts"
        ]
    }

    return report


if __name__ == "__main__":
    rep = migrate_production_cache(dry_run=False)
    print("\n" + "=" * 60)
    print("CACHE MIGRATION REPORT")
    print("=" * 60)
    for k, v in rep.items():
        print(f"  {k}: {v}")
    print("=" * 60)
